### ISSUE TITLE
Mechanic Crafting Suggestions 

### ISSUE THREAD

**Issue by WarPoet1** [BrandonSnippets/Lunar-Reports#5]
Supercharger Turbo - 20 alu

Vehicle Armor - 15 steel 15 iron

Tier 1 Engine - 2 alu 2 steel
Tier 2 Engine - 4 alu 4 steel
Tier 3 Engine - 8 alu 8 steel
Tier 4 Engine - 16 alu 16 steel
Tier 5 Engine - 32 alu 32 steel

Tier 1 Transmission - 4 steel 2 alu
Tier 2 Transmission - 8 steel 4 alu
Tier 3 Transmission - 12 steel 8 alu
Tier 4 Transmission - 16 steel 12 alu

Tier 1 Brakes -  iron 5
Tier 2 Brakes -  iron 10
Tier 3 Brakes -  iron 20

Tier 1 Suspension - 4 steel
Tier 2 Suspension - 8 steel
Tier 3 Suspension - 12 steel
Tier 4 Suspension - 16 steel 16 alu
Tier 5 Suspension - 20 steel 20 alu

Bulletproof Tires - rubber 20 alu 10

Drift Tires . rubber 20

Tier 1 Oil Pump -  5 alu
Tier 2 Oil Pump - 10 alu
Tier 3 Oil Pump - 15 alu

Tier 1 Drive Shaft - 5 alu 2 rubber
Tier 2 Drive Shaft - 10 alu 4 rubber
Tier 3 Drive Shaft - 15 alu 6 rubber

Tier 1 Cylinder Head - 5 alu
Tier 2 Cylinder Head - 10 alu
Tier 3 Cylinder Head - 15 alu

Tier 1 Battery Cables - rubber 2 copper 5
Tier 2 Battery Cables - rubber 4 copper 10
Tier 3 Battery Cables - rubber 6 copper 15

Tier 1 Fuel Tank - plastic 5
Tier 2 Fuel Tank - plastic 10
Tier 3 Fuel Tank - plastic 15

Race Harness - 3 alu 3 plastic

AntiLag - 5 steel

**Comment by WarPoet1** [comment]
Binoculars don't work

**Comment by WarPoet1** [comment]
GABs housing MLO

**Comment by WarPoet1** [comment]
CROW EX ATM

**Comment by BrandonSnippets** [comment]
Thanks for the suggestions and reports 👍🏻
